use crate::state::{
    audio::AudioDeviceSelection,
    drums::DrumVoice,
    midi::{MidiBindingTarget, MidiChannel},
    project::ProjectTarget,
    synth::{LfoTarget, LfoWaveform, Waveform},
    ui::{VisualFx, SettingsPage, VisualMode},
};

#[derive(Clone, Debug, PartialEq)]
pub enum AppCommand {
    ToggleHelp,
    ToggleSettings,
    SetSettingsPage(SettingsPage),
    SetVisualMode(VisualMode),
    SetVisualFx(VisualFx),
    SetVisualFxDepth(f32),
    ToggleScopeDrums,
    NoteOnKeyboard(i8),
    NoteOffKeyboard,
    NoteOnMidi(u8),
    NoteOffMidi(u8),
    SetBaseMidi(i16),
    SetVolume(f32),
    SetAttack(f32),
    SetRelease(f32),
    SetGateMode(bool),
    SelectOscillator(usize),
    SetWaveform {
        oscillator: usize,
        waveform: Waveform,
    },
    SetOscillatorLevel {
        oscillator: usize,
        level: f32,
    },
    SetOscillatorOctave {
        oscillator: usize,
        octave: i8,
    },
    SetOscillatorDetune {
        oscillator: usize,
        cents: f32,
    },
    SetVoices(u8),
    ToggleFilter,
    SetCutoff(f32),
    SetResonance(f32),
    SetLfoWaveform(LfoWaveform),
    SetLfoRate(f32),
    SetLfoDepth(f32),
    SetLfoTarget(LfoTarget),
    SetFxDrive(f32),
    SetFxDelayMix(f32),
    SetFxDelayFeedback(f32),
    SetFxDelayTime(f32),
    SetFxWarmth(f32),
    SetFxAir(f32),
    SetFxReverb(f32),
    ToggleSequencer,
    SetDrumStep {
        voice: DrumVoice,
        step: usize,
        enabled: bool,
    },
    ClearDrumVoice(DrumVoice),
    ClearAllDrums,
    SetDrumVolume {
        voice: DrumVoice,
        level: f32,
    },
    SetDrumBank(usize),
    SetBpm(f32),
    StartLoopReplace,
    StopLoopRecording,
    StartLoopOverdub,
    StopLoopOverdub,
    ToggleLoopPlayback,
    UndoLoopOverdub,
    ClearLoop,
    ToggleGlobalRecording,
    SetMidiEnabled(bool),
    SelectMidiChannel(MidiChannel),
    SetMidiNoteInput(bool),
    SetMidiPadInput(bool),
    SetMidiNoteRemap {
        src: u8,
        dst: Option<u8>,
    },
    BindMidiTarget {
        target: MidiBindingTarget,
        value: Option<u8>,
    },
    SetAudioOutput(AudioDeviceSelection),
    SetAudioInput(AudioDeviceSelection),
    RefreshAudioDevices,
    RefreshMidiDevices,
    SaveProject(ProjectTarget),
    LoadProject(ProjectTarget),
}
